#!/bin/bash

if [ $# -lt 2 ]
then
	echo "usage: ./createComponent projectName componentName"
	exit 0	
fi

cd ../components/myComponents
mkdir $1
cp zzTemplate/Makefile $1/Makefile
cp zzTemplate/template.c $1/$1.c
cp zzTemplate/template.h $1/$1.h

proj_name=$1
comp_name=$2

sed -i "s/PROJECT_NAME/$proj_name/g" $1/Makefile
sed -i "s/PROJECT_NAME/$proj_name/g" $1/$1.c
sed -i "s/PROJECT_NAME/$proj_name/g" $1/$1.h
sed -i "s/MY_COMP_NAME/$comp_name/g" $1/$1.c
sed -i "s/MY_COMP_NAME/$comp_name/g" $1/$1.h