#!/bin/bash

if [ $# -lt 1 ]
then
	echo "usage: ./createComponent imageName"
	exit 0	
fi

cd ../cmp_images
mkdir $1
cp zzTemplate/image-conf.h $1/image-conf.h
cp zzTemplate/image-init.c $1/image-init.c
cp zzTemplate/Makefile.image $1/Makefile.image

img_name=$1

sed -i "s/IMAGE_NAME/$img_name/g" $1/Makefile.image